package org.mortgages;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Employee implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "Name")
   private java.lang.String name;
   @org.kie.api.definition.type.Label(value = "Age")
   private java.util.List<java.lang.Integer> age;

   public Employee()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.util.List<java.lang.Integer> getAge()
   {
      return this.age;
   }

   public void setAge(java.util.List<java.lang.Integer> age)
   {
      this.age = age;
   }

   public Employee(java.lang.String name, java.util.List<java.lang.Integer> age)
   {
      this.name = name;
      this.age = age;
   }

}